services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: notesdb
      MYSQL_USER: noteuser
      MYSQL_PASSWORD: Note@007
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot1234" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: note-application-container
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/notesdb
      SPRING_DATASOURCE_USERNAME: noteuser
      SPRING_DATASOURCE_PASSWORD: Note@007
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
